# Generated by Django 4.0.5 on 2022-06-16 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='username',
        ),
    ]
