# Generated by Django 4.0.5 on 2022-06-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_survey_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
