# Generated by Django 4.0.5 on 2022-06-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_survey_finished'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surveyID', models.CharField(default='', max_length=255)),
                ('sessionID', models.CharField(default='', max_length=255)),
                ('customerID', models.CharField(default='', max_length=255)),
                ('didBuy', models.IntegerField(default=-1)),
                ('sellerExp', models.IntegerField(default=-1)),
                ('prodQual', models.IntegerField(default=-1)),
                ('anyMsg', models.TextField(default='')),
            ],
        ),
    ]
